version: "2"

run:
  go: '1.24'
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - errname
    - gocritic
    - nilerr
    - interfacebloat
    - usestdlibvars
  settings:
    dupl:
      # Increased threshold for structural duplication in controller/service patterns
      # These duplications are intentional - each resource type needs similar boilerplate
      threshold: 300
    revive:
      enable-all-rules: true
      rules:
        - name: exported
          disabled: true
        - name: line-length-limit
          arguments: [150]
        - name: function-length
          disabled: true
        - name: add-constant
          disabled: true
        - name: use-any
          disabled: true
    interfacebloat:
      max: 15
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: api/*
      # Allow dot imports in test files for Ginkgo/Gomega
      - linters:
          - revive
        path: _test\.go
        text: "dot-imports"
      # Exclude sync controllers from dupl - structural duplication is intentional
      # Each sync controller follows the same pattern for its resource type
      - linters:
          - dupl
        path: internal/sync/
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/StringKe/cloudflare-operator
