# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# GoReleaser configuration for cloudflare-operator
# Documentation: https://goreleaser.com

version: 2

project_name: cloudflare-operator

before:
  hooks:
    - go mod tidy

builds:
  - id: manager
    binary: manager
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - config/crd/bases/*.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Sign the checksum file
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: checksum
    output: true

# Sign container images
docker_signs:
  - cmd: cosign
    args:
      - sign
      - "--yes"
      - "${artifact}"
    artifacts: all
    output: true

# SBOM generation
sboms:
  - artifacts: archive

# Release configuration
release:
  github:
    owner: StringKe
    name: cloudflare-operator
  draft: false
  prerelease: auto
  mode: replace
  extra_files:
    - glob: ./dist/*.yaml

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore\\(deps\\):"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# Announce configuration (optional)
announce:
  skip: "true"
