//go:build !ignore_autogenerated

/*
Copyright 2025 Adyanth H.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccountIdentifier) DeepCopyInto(out *CloudflareAccountIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccountIdentifier.
func (in *CloudflareAccountIdentifier) DeepCopy() *CloudflareAccountIdentifier {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccountIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccountRef) DeepCopyInto(out *CloudflareAccountRef) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccountRef.
func (in *CloudflareAccountRef) DeepCopy() *CloudflareAccountRef {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareCredentials) DeepCopyInto(out *CloudflareCredentials) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareCredentials.
func (in *CloudflareCredentials) DeepCopy() *CloudflareCredentials {
	if in == nil {
		return nil
	}
	out := new(CloudflareCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRef) DeepCopyInto(out *CloudflareRef) {
	*out = *in
	out.Credentials = in.Credentials
	out.Account = in.Account
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(CloudflareZoneIdentifier)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRef.
func (in *CloudflareRef) DeepCopy() *CloudflareRef {
	if in == nil {
		return nil
	}
	out := new(CloudflareRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneIdentifier) DeepCopyInto(out *CloudflareZoneIdentifier) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneIdentifier.
func (in *CloudflareZoneIdentifier) DeepCopy() *CloudflareZoneIdentifier {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneRef) DeepCopyInto(out *CloudflareZoneRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneRef.
func (in *CloudflareZoneRef) DeepCopy() *CloudflareZoneRef {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExistingTunnelRef) DeepCopyInto(out *ExistingTunnelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExistingTunnelRef.
func (in *ExistingTunnelRef) DeepCopy() *ExistingTunnelRef {
	if in == nil {
		return nil
	}
	out := new(ExistingTunnelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainEntry) DeepCopyInto(out *FallbackDomainEntry) {
	*out = *in
	if in.DNSServer != nil {
		in, out := &in.DNSServer, &out.DNSServer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainEntry.
func (in *FallbackDomainEntry) DeepCopy() *FallbackDomainEntry {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewTunnelSpec) DeepCopyInto(out *NewTunnelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewTunnelSpec.
func (in *NewTunnelSpec) DeepCopy() *NewTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(NewTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelEntry) DeepCopyInto(out *SplitTunnelEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelEntry.
func (in *SplitTunnelEntry) DeepCopy() *SplitTunnelEntry {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelReference) DeepCopyInto(out *TunnelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelReference.
func (in *TunnelReference) DeepCopy() *TunnelReference {
	if in == nil {
		return nil
	}
	out := new(TunnelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelSource) DeepCopyInto(out *TunnelSource) {
	*out = *in
	if in.ExistingTunnel != nil {
		in, out := &in.ExistingTunnel, &out.ExistingTunnel
		*out = new(ExistingTunnelRef)
		**out = **in
	}
	if in.NewTunnel != nil {
		in, out := &in.NewTunnel, &out.NewTunnel
		*out = new(NewTunnelSpec)
		**out = **in
	}
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelSource.
func (in *TunnelSource) DeepCopy() *TunnelSource {
	if in == nil {
		return nil
	}
	out := new(TunnelSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkReference) DeepCopyInto(out *VirtualNetworkReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkReference.
func (in *VirtualNetworkReference) DeepCopy() *VirtualNetworkReference {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPRoutingConfig) DeepCopyInto(out *WARPRoutingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPRoutingConfig.
func (in *WARPRoutingConfig) DeepCopy() *WARPRoutingConfig {
	if in == nil {
		return nil
	}
	out := new(WARPRoutingConfig)
	in.DeepCopyInto(out)
	return out
}
