// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/StringKe/cloudflare-operator/internal/clients/cf (interfaces: CloudflareClient)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_client.go -package=mock github.com/StringKe/cloudflare-operator/internal/clients/cf CloudflareClient
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	cf "github.com/StringKe/cloudflare-operator/internal/clients/cf"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudflareClient is a mock of CloudflareClient interface.
type MockCloudflareClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudflareClientMockRecorder
	isgomock struct{}
}

// MockCloudflareClientMockRecorder is the mock recorder for MockCloudflareClient.
type MockCloudflareClientMockRecorder struct {
	mock *MockCloudflareClient
}

// NewMockCloudflareClient creates a new mock instance.
func NewMockCloudflareClient(ctrl *gomock.Controller) *MockCloudflareClient {
	mock := &MockCloudflareClient{ctrl: ctrl}
	mock.recorder = &MockCloudflareClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudflareClient) EXPECT() *MockCloudflareClientMockRecorder {
	return m.recorder
}

// CreateAccessApplication mocks base method.
func (m *MockCloudflareClient) CreateAccessApplication(params cf.AccessApplicationParams) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessApplication", params)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessApplication indicates an expected call of CreateAccessApplication.
func (mr *MockCloudflareClientMockRecorder) CreateAccessApplication(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessApplication), params)
}

// CreateAccessGroup mocks base method.
func (m *MockCloudflareClient) CreateAccessGroup(params cf.AccessGroupParams) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessGroup", params)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessGroup indicates an expected call of CreateAccessGroup.
func (mr *MockCloudflareClientMockRecorder) CreateAccessGroup(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessGroup), params)
}

// CreateAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) CreateAccessIdentityProvider(params cf.AccessIdentityProviderParams) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessIdentityProvider", params)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessIdentityProvider indicates an expected call of CreateAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) CreateAccessIdentityProvider(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessIdentityProvider), params)
}

// CreateAccessServiceToken mocks base method.
func (m *MockCloudflareClient) CreateAccessServiceToken(name, duration string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessServiceToken", name, duration)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessServiceToken indicates an expected call of CreateAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) CreateAccessServiceToken(name, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessServiceToken), name, duration)
}

// CreateDNSRecord mocks base method.
func (m *MockCloudflareClient) CreateDNSRecord(params cf.DNSRecordParams) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDNSRecord", params)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDNSRecord indicates an expected call of CreateDNSRecord.
func (mr *MockCloudflareClientMockRecorder) CreateDNSRecord(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).CreateDNSRecord), params)
}

// CreateDevicePostureRule mocks base method.
func (m *MockCloudflareClient) CreateDevicePostureRule(params cf.DevicePostureRuleParams) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevicePostureRule", params)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevicePostureRule indicates an expected call of CreateDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) CreateDevicePostureRule(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).CreateDevicePostureRule), params)
}

// CreateGatewayList mocks base method.
func (m *MockCloudflareClient) CreateGatewayList(params cf.GatewayListParams) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGatewayList", params)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGatewayList indicates an expected call of CreateGatewayList.
func (mr *MockCloudflareClientMockRecorder) CreateGatewayList(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).CreateGatewayList), params)
}

// CreateGatewayRule mocks base method.
func (m *MockCloudflareClient) CreateGatewayRule(params cf.GatewayRuleParams) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGatewayRule", params)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGatewayRule indicates an expected call of CreateGatewayRule.
func (mr *MockCloudflareClientMockRecorder) CreateGatewayRule(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).CreateGatewayRule), params)
}

// CreateTunnel mocks base method.
func (m *MockCloudflareClient) CreateTunnel() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTunnel")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTunnel indicates an expected call of CreateTunnel.
func (mr *MockCloudflareClientMockRecorder) CreateTunnel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTunnel", reflect.TypeOf((*MockCloudflareClient)(nil).CreateTunnel))
}

// CreateTunnelRoute mocks base method.
func (m *MockCloudflareClient) CreateTunnelRoute(params cf.TunnelRouteParams) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTunnelRoute", params)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTunnelRoute indicates an expected call of CreateTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) CreateTunnelRoute(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).CreateTunnelRoute), params)
}

// CreateVirtualNetwork mocks base method.
func (m *MockCloudflareClient) CreateVirtualNetwork(params cf.VirtualNetworkParams) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVirtualNetwork", params)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVirtualNetwork indicates an expected call of CreateVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) CreateVirtualNetwork(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).CreateVirtualNetwork), params)
}

// CreateWARPConnector mocks base method.
func (m *MockCloudflareClient) CreateWARPConnector(name string) (*cf.WARPConnectorResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWARPConnector", name)
	ret0, _ := ret[0].(*cf.WARPConnectorResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWARPConnector indicates an expected call of CreateWARPConnector.
func (mr *MockCloudflareClientMockRecorder) CreateWARPConnector(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWARPConnector", reflect.TypeOf((*MockCloudflareClient)(nil).CreateWARPConnector), name)
}

// DeleteAccessApplication mocks base method.
func (m *MockCloudflareClient) DeleteAccessApplication(applicationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessApplication", applicationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessApplication indicates an expected call of DeleteAccessApplication.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessApplication(applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessApplication), applicationID)
}

// DeleteAccessGroup mocks base method.
func (m *MockCloudflareClient) DeleteAccessGroup(groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessGroup", groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessGroup indicates an expected call of DeleteAccessGroup.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessGroup(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessGroup), groupID)
}

// DeleteAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) DeleteAccessIdentityProvider(idpID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessIdentityProvider", idpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessIdentityProvider indicates an expected call of DeleteAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessIdentityProvider(idpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessIdentityProvider), idpID)
}

// DeleteAccessServiceToken mocks base method.
func (m *MockCloudflareClient) DeleteAccessServiceToken(tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessServiceToken", tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessServiceToken indicates an expected call of DeleteAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessServiceToken(tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessServiceToken), tokenID)
}

// DeleteDNSId mocks base method.
func (m *MockCloudflareClient) DeleteDNSId(fqdn, dnsID string, created bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSId", fqdn, dnsID, created)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSId indicates an expected call of DeleteDNSId.
func (mr *MockCloudflareClientMockRecorder) DeleteDNSId(fqdn, dnsID, created any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSId", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDNSId), fqdn, dnsID, created)
}

// DeleteDNSRecord mocks base method.
func (m *MockCloudflareClient) DeleteDNSRecord(zoneID, recordID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSRecord", zoneID, recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSRecord indicates an expected call of DeleteDNSRecord.
func (mr *MockCloudflareClientMockRecorder) DeleteDNSRecord(zoneID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDNSRecord), zoneID, recordID)
}

// DeleteDevicePostureRule mocks base method.
func (m *MockCloudflareClient) DeleteDevicePostureRule(ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevicePostureRule", ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevicePostureRule indicates an expected call of DeleteDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) DeleteDevicePostureRule(ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDevicePostureRule), ruleID)
}

// DeleteGatewayList mocks base method.
func (m *MockCloudflareClient) DeleteGatewayList(listID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGatewayList", listID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGatewayList indicates an expected call of DeleteGatewayList.
func (mr *MockCloudflareClientMockRecorder) DeleteGatewayList(listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteGatewayList), listID)
}

// DeleteGatewayRule mocks base method.
func (m *MockCloudflareClient) DeleteGatewayRule(ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGatewayRule", ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGatewayRule indicates an expected call of DeleteGatewayRule.
func (mr *MockCloudflareClientMockRecorder) DeleteGatewayRule(ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteGatewayRule), ruleID)
}

// DeleteTunnel mocks base method.
func (m *MockCloudflareClient) DeleteTunnel() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTunnel")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTunnel indicates an expected call of DeleteTunnel.
func (mr *MockCloudflareClientMockRecorder) DeleteTunnel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTunnel", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteTunnel))
}

// DeleteTunnelRoute mocks base method.
func (m *MockCloudflareClient) DeleteTunnelRoute(network, virtualNetworkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTunnelRoute", network, virtualNetworkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTunnelRoute indicates an expected call of DeleteTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) DeleteTunnelRoute(network, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteTunnelRoute), network, virtualNetworkID)
}

// DeleteVirtualNetwork mocks base method.
func (m *MockCloudflareClient) DeleteVirtualNetwork(virtualNetworkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVirtualNetwork", virtualNetworkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVirtualNetwork indicates an expected call of DeleteVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) DeleteVirtualNetwork(virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteVirtualNetwork), virtualNetworkID)
}

// DeleteWARPConnector mocks base method.
func (m *MockCloudflareClient) DeleteWARPConnector(connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWARPConnector", connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWARPConnector indicates an expected call of DeleteWARPConnector.
func (mr *MockCloudflareClientMockRecorder) DeleteWARPConnector(connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWARPConnector", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteWARPConnector), connectorID)
}

// GetAccessApplication mocks base method.
func (m *MockCloudflareClient) GetAccessApplication(applicationID string) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessApplication", applicationID)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessApplication indicates an expected call of GetAccessApplication.
func (mr *MockCloudflareClientMockRecorder) GetAccessApplication(applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessApplication), applicationID)
}

// GetAccessGroup mocks base method.
func (m *MockCloudflareClient) GetAccessGroup(groupID string) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessGroup", groupID)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessGroup indicates an expected call of GetAccessGroup.
func (mr *MockCloudflareClientMockRecorder) GetAccessGroup(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessGroup), groupID)
}

// GetAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) GetAccessIdentityProvider(idpID string) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessIdentityProvider", idpID)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessIdentityProvider indicates an expected call of GetAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) GetAccessIdentityProvider(idpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessIdentityProvider), idpID)
}

// GetAccessServiceTokenByName mocks base method.
func (m *MockCloudflareClient) GetAccessServiceTokenByName(name string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessServiceTokenByName", name)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessServiceTokenByName indicates an expected call of GetAccessServiceTokenByName.
func (mr *MockCloudflareClientMockRecorder) GetAccessServiceTokenByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessServiceTokenByName", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessServiceTokenByName), name)
}

// GetAccountId mocks base method.
func (m *MockCloudflareClient) GetAccountId() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountId")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId.
func (mr *MockCloudflareClientMockRecorder) GetAccountId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccountId))
}

// GetDNSCNameId mocks base method.
func (m *MockCloudflareClient) GetDNSCNameId(fqdn string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSCNameId", fqdn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSCNameId indicates an expected call of GetDNSCNameId.
func (mr *MockCloudflareClientMockRecorder) GetDNSCNameId(fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSCNameId", reflect.TypeOf((*MockCloudflareClient)(nil).GetDNSCNameId), fqdn)
}

// GetDNSRecord mocks base method.
func (m *MockCloudflareClient) GetDNSRecord(zoneID, recordID string) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSRecord", zoneID, recordID)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSRecord indicates an expected call of GetDNSRecord.
func (mr *MockCloudflareClientMockRecorder) GetDNSRecord(zoneID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).GetDNSRecord), zoneID, recordID)
}

// GetDevicePostureRule mocks base method.
func (m *MockCloudflareClient) GetDevicePostureRule(ruleID string) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePostureRule", ruleID)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePostureRule indicates an expected call of GetDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) GetDevicePostureRule(ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).GetDevicePostureRule), ruleID)
}

// GetFallbackDomains mocks base method.
func (m *MockCloudflareClient) GetFallbackDomains() ([]cf.FallbackDomainEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFallbackDomains")
	ret0, _ := ret[0].([]cf.FallbackDomainEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFallbackDomains indicates an expected call of GetFallbackDomains.
func (mr *MockCloudflareClientMockRecorder) GetFallbackDomains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFallbackDomains", reflect.TypeOf((*MockCloudflareClient)(nil).GetFallbackDomains))
}

// GetGatewayList mocks base method.
func (m *MockCloudflareClient) GetGatewayList(listID string) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayList", listID)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayList indicates an expected call of GetGatewayList.
func (mr *MockCloudflareClientMockRecorder) GetGatewayList(listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).GetGatewayList), listID)
}

// GetGatewayRule mocks base method.
func (m *MockCloudflareClient) GetGatewayRule(ruleID string) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayRule", ruleID)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayRule indicates an expected call of GetGatewayRule.
func (mr *MockCloudflareClientMockRecorder) GetGatewayRule(ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).GetGatewayRule), ruleID)
}

// GetManagedDnsTxt mocks base method.
func (m *MockCloudflareClient) GetManagedDnsTxt(fqdn string) (string, cf.DnsManagedRecordTxt, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagedDnsTxt", fqdn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(cf.DnsManagedRecordTxt)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetManagedDnsTxt indicates an expected call of GetManagedDnsTxt.
func (mr *MockCloudflareClientMockRecorder) GetManagedDnsTxt(fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedDnsTxt", reflect.TypeOf((*MockCloudflareClient)(nil).GetManagedDnsTxt), fqdn)
}

// GetSplitTunnelExclude mocks base method.
func (m *MockCloudflareClient) GetSplitTunnelExclude() ([]cf.SplitTunnelEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSplitTunnelExclude")
	ret0, _ := ret[0].([]cf.SplitTunnelEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSplitTunnelExclude indicates an expected call of GetSplitTunnelExclude.
func (mr *MockCloudflareClientMockRecorder) GetSplitTunnelExclude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSplitTunnelExclude", reflect.TypeOf((*MockCloudflareClient)(nil).GetSplitTunnelExclude))
}

// GetSplitTunnelInclude mocks base method.
func (m *MockCloudflareClient) GetSplitTunnelInclude() ([]cf.SplitTunnelEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSplitTunnelInclude")
	ret0, _ := ret[0].([]cf.SplitTunnelEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSplitTunnelInclude indicates an expected call of GetSplitTunnelInclude.
func (mr *MockCloudflareClientMockRecorder) GetSplitTunnelInclude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSplitTunnelInclude", reflect.TypeOf((*MockCloudflareClient)(nil).GetSplitTunnelInclude))
}

// GetTunnelCreds mocks base method.
func (m *MockCloudflareClient) GetTunnelCreds(tunnelSecret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelCreds", tunnelSecret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelCreds indicates an expected call of GetTunnelCreds.
func (mr *MockCloudflareClientMockRecorder) GetTunnelCreds(tunnelSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelCreds", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelCreds), tunnelSecret)
}

// GetTunnelId mocks base method.
func (m *MockCloudflareClient) GetTunnelId() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelId")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelId indicates an expected call of GetTunnelId.
func (mr *MockCloudflareClientMockRecorder) GetTunnelId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelId", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelId))
}

// GetTunnelRoute mocks base method.
func (m *MockCloudflareClient) GetTunnelRoute(network, virtualNetworkID string) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelRoute", network, virtualNetworkID)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelRoute indicates an expected call of GetTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) GetTunnelRoute(network, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelRoute), network, virtualNetworkID)
}

// GetVirtualNetwork mocks base method.
func (m *MockCloudflareClient) GetVirtualNetwork(virtualNetworkID string) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualNetwork", virtualNetworkID)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualNetwork indicates an expected call of GetVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) GetVirtualNetwork(virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).GetVirtualNetwork), virtualNetworkID)
}

// GetVirtualNetworkByName mocks base method.
func (m *MockCloudflareClient) GetVirtualNetworkByName(name string) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualNetworkByName", name)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualNetworkByName indicates an expected call of GetVirtualNetworkByName.
func (mr *MockCloudflareClientMockRecorder) GetVirtualNetworkByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualNetworkByName", reflect.TypeOf((*MockCloudflareClient)(nil).GetVirtualNetworkByName), name)
}

// GetWARPConnectorToken mocks base method.
func (m *MockCloudflareClient) GetWARPConnectorToken(connectorID string) (*cf.WARPConnectorTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWARPConnectorToken", connectorID)
	ret0, _ := ret[0].(*cf.WARPConnectorTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWARPConnectorToken indicates an expected call of GetWARPConnectorToken.
func (mr *MockCloudflareClientMockRecorder) GetWARPConnectorToken(connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWARPConnectorToken", reflect.TypeOf((*MockCloudflareClient)(nil).GetWARPConnectorToken), connectorID)
}

// GetZoneId mocks base method.
func (m *MockCloudflareClient) GetZoneId() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneId")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneId indicates an expected call of GetZoneId.
func (mr *MockCloudflareClientMockRecorder) GetZoneId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneId", reflect.TypeOf((*MockCloudflareClient)(nil).GetZoneId))
}

// InsertOrUpdateCName mocks base method.
func (m *MockCloudflareClient) InsertOrUpdateCName(fqdn, dnsID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdateCName", fqdn, dnsID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOrUpdateCName indicates an expected call of InsertOrUpdateCName.
func (mr *MockCloudflareClientMockRecorder) InsertOrUpdateCName(fqdn, dnsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdateCName", reflect.TypeOf((*MockCloudflareClient)(nil).InsertOrUpdateCName), fqdn, dnsID)
}

// InsertOrUpdateTXT mocks base method.
func (m *MockCloudflareClient) InsertOrUpdateTXT(fqdn, txtID, dnsID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdateTXT", fqdn, txtID, dnsID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdateTXT indicates an expected call of InsertOrUpdateTXT.
func (mr *MockCloudflareClientMockRecorder) InsertOrUpdateTXT(fqdn, txtID, dnsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdateTXT", reflect.TypeOf((*MockCloudflareClient)(nil).InsertOrUpdateTXT), fqdn, txtID, dnsID)
}

// ListAccessApplicationsByName mocks base method.
func (m *MockCloudflareClient) ListAccessApplicationsByName(name string) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessApplicationsByName", name)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessApplicationsByName indicates an expected call of ListAccessApplicationsByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessApplicationsByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessApplicationsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessApplicationsByName), name)
}

// ListAccessGroupsByName mocks base method.
func (m *MockCloudflareClient) ListAccessGroupsByName(name string) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessGroupsByName", name)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessGroupsByName indicates an expected call of ListAccessGroupsByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessGroupsByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessGroupsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessGroupsByName), name)
}

// ListAccessIdentityProvidersByName mocks base method.
func (m *MockCloudflareClient) ListAccessIdentityProvidersByName(name string) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessIdentityProvidersByName", name)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessIdentityProvidersByName indicates an expected call of ListAccessIdentityProvidersByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessIdentityProvidersByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessIdentityProvidersByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessIdentityProvidersByName), name)
}

// ListDevicePostureRulesByName mocks base method.
func (m *MockCloudflareClient) ListDevicePostureRulesByName(name string) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevicePostureRulesByName", name)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevicePostureRulesByName indicates an expected call of ListDevicePostureRulesByName.
func (mr *MockCloudflareClientMockRecorder) ListDevicePostureRulesByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevicePostureRulesByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListDevicePostureRulesByName), name)
}

// ListGatewayListsByName mocks base method.
func (m *MockCloudflareClient) ListGatewayListsByName(name string) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGatewayListsByName", name)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGatewayListsByName indicates an expected call of ListGatewayListsByName.
func (mr *MockCloudflareClientMockRecorder) ListGatewayListsByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGatewayListsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListGatewayListsByName), name)
}

// ListGatewayRulesByName mocks base method.
func (m *MockCloudflareClient) ListGatewayRulesByName(name string) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGatewayRulesByName", name)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGatewayRulesByName indicates an expected call of ListGatewayRulesByName.
func (mr *MockCloudflareClientMockRecorder) ListGatewayRulesByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGatewayRulesByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListGatewayRulesByName), name)
}

// RefreshAccessServiceToken mocks base method.
func (m *MockCloudflareClient) RefreshAccessServiceToken(tokenID string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessServiceToken", tokenID)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessServiceToken indicates an expected call of RefreshAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) RefreshAccessServiceToken(tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).RefreshAccessServiceToken), tokenID)
}

// UpdateAccessApplication mocks base method.
func (m *MockCloudflareClient) UpdateAccessApplication(applicationID string, params cf.AccessApplicationParams) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessApplication", applicationID, params)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessApplication indicates an expected call of UpdateAccessApplication.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessApplication(applicationID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessApplication), applicationID, params)
}

// UpdateAccessGroup mocks base method.
func (m *MockCloudflareClient) UpdateAccessGroup(groupID string, params cf.AccessGroupParams) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessGroup", groupID, params)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessGroup indicates an expected call of UpdateAccessGroup.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessGroup(groupID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessGroup), groupID, params)
}

// UpdateAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) UpdateAccessIdentityProvider(idpID string, params cf.AccessIdentityProviderParams) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessIdentityProvider", idpID, params)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessIdentityProvider indicates an expected call of UpdateAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessIdentityProvider(idpID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessIdentityProvider), idpID, params)
}

// UpdateAccessServiceToken mocks base method.
func (m *MockCloudflareClient) UpdateAccessServiceToken(tokenID, name, duration string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessServiceToken", tokenID, name, duration)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessServiceToken indicates an expected call of UpdateAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessServiceToken(tokenID, name, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessServiceToken), tokenID, name, duration)
}

// UpdateDNSRecord mocks base method.
func (m *MockCloudflareClient) UpdateDNSRecord(zoneID, recordID string, params cf.DNSRecordParams) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDNSRecord", zoneID, recordID, params)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDNSRecord indicates an expected call of UpdateDNSRecord.
func (mr *MockCloudflareClientMockRecorder) UpdateDNSRecord(zoneID, recordID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateDNSRecord), zoneID, recordID, params)
}

// UpdateDevicePostureRule mocks base method.
func (m *MockCloudflareClient) UpdateDevicePostureRule(ruleID string, params cf.DevicePostureRuleParams) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevicePostureRule", ruleID, params)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevicePostureRule indicates an expected call of UpdateDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) UpdateDevicePostureRule(ruleID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateDevicePostureRule), ruleID, params)
}

// UpdateFallbackDomains mocks base method.
func (m *MockCloudflareClient) UpdateFallbackDomains(entries []cf.FallbackDomainEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFallbackDomains", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFallbackDomains indicates an expected call of UpdateFallbackDomains.
func (mr *MockCloudflareClientMockRecorder) UpdateFallbackDomains(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFallbackDomains", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateFallbackDomains), entries)
}

// UpdateGatewayConfiguration mocks base method.
func (m *MockCloudflareClient) UpdateGatewayConfiguration(params cf.GatewayConfigurationParams) (*cf.GatewayConfigurationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayConfiguration", params)
	ret0, _ := ret[0].(*cf.GatewayConfigurationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayConfiguration indicates an expected call of UpdateGatewayConfiguration.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayConfiguration(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayConfiguration", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayConfiguration), params)
}

// UpdateGatewayList mocks base method.
func (m *MockCloudflareClient) UpdateGatewayList(listID string, params cf.GatewayListParams) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayList", listID, params)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayList indicates an expected call of UpdateGatewayList.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayList(listID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayList), listID, params)
}

// UpdateGatewayRule mocks base method.
func (m *MockCloudflareClient) UpdateGatewayRule(ruleID string, params cf.GatewayRuleParams) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayRule", ruleID, params)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayRule indicates an expected call of UpdateGatewayRule.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayRule(ruleID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayRule), ruleID, params)
}

// UpdateSplitTunnelExclude mocks base method.
func (m *MockCloudflareClient) UpdateSplitTunnelExclude(entries []cf.SplitTunnelEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSplitTunnelExclude", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSplitTunnelExclude indicates an expected call of UpdateSplitTunnelExclude.
func (mr *MockCloudflareClientMockRecorder) UpdateSplitTunnelExclude(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSplitTunnelExclude", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateSplitTunnelExclude), entries)
}

// UpdateSplitTunnelInclude mocks base method.
func (m *MockCloudflareClient) UpdateSplitTunnelInclude(entries []cf.SplitTunnelEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSplitTunnelInclude", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSplitTunnelInclude indicates an expected call of UpdateSplitTunnelInclude.
func (mr *MockCloudflareClientMockRecorder) UpdateSplitTunnelInclude(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSplitTunnelInclude", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateSplitTunnelInclude), entries)
}

// UpdateTunnelRoute mocks base method.
func (m *MockCloudflareClient) UpdateTunnelRoute(network string, params cf.TunnelRouteParams) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTunnelRoute", network, params)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTunnelRoute indicates an expected call of UpdateTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) UpdateTunnelRoute(network, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateTunnelRoute), network, params)
}

// UpdateVirtualNetwork mocks base method.
func (m *MockCloudflareClient) UpdateVirtualNetwork(virtualNetworkID string, params cf.VirtualNetworkParams) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVirtualNetwork", virtualNetworkID, params)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVirtualNetwork indicates an expected call of UpdateVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) UpdateVirtualNetwork(virtualNetworkID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateVirtualNetwork), virtualNetworkID, params)
}

// ValidateAll mocks base method.
func (m *MockCloudflareClient) ValidateAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAll indicates an expected call of ValidateAll.
func (mr *MockCloudflareClientMockRecorder) ValidateAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAll", reflect.TypeOf((*MockCloudflareClient)(nil).ValidateAll))
}
