// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/StringKe/cloudflare-operator/internal/clients/cf (interfaces: CloudflareClient)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_client.go -package=mock github.com/StringKe/cloudflare-operator/internal/clients/cf CloudflareClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	cf "github.com/StringKe/cloudflare-operator/internal/clients/cf"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudflareClient is a mock of CloudflareClient interface.
type MockCloudflareClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudflareClientMockRecorder
	isgomock struct{}
}

// MockCloudflareClientMockRecorder is the mock recorder for MockCloudflareClient.
type MockCloudflareClientMockRecorder struct {
	mock *MockCloudflareClient
}

// NewMockCloudflareClient creates a new mock instance.
func NewMockCloudflareClient(ctrl *gomock.Controller) *MockCloudflareClient {
	mock := &MockCloudflareClient{ctrl: ctrl}
	mock.recorder = &MockCloudflareClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudflareClient) EXPECT() *MockCloudflareClientMockRecorder {
	return m.recorder
}

// CreateAccessApplication mocks base method.
func (m *MockCloudflareClient) CreateAccessApplication(ctx context.Context, params cf.AccessApplicationParams) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessApplication", ctx, params)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessApplication indicates an expected call of CreateAccessApplication.
func (mr *MockCloudflareClientMockRecorder) CreateAccessApplication(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessApplication), ctx, params)
}

// CreateAccessGroup mocks base method.
func (m *MockCloudflareClient) CreateAccessGroup(ctx context.Context, params cf.AccessGroupParams) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessGroup", ctx, params)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessGroup indicates an expected call of CreateAccessGroup.
func (mr *MockCloudflareClientMockRecorder) CreateAccessGroup(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessGroup), ctx, params)
}

// CreateAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) CreateAccessIdentityProvider(ctx context.Context, params cf.AccessIdentityProviderParams) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessIdentityProvider", ctx, params)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessIdentityProvider indicates an expected call of CreateAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) CreateAccessIdentityProvider(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessIdentityProvider), ctx, params)
}

// CreateAccessPolicy mocks base method.
func (m *MockCloudflareClient) CreateAccessPolicy(ctx context.Context, params cf.AccessPolicyParams) (*cf.AccessPolicyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPolicy", ctx, params)
	ret0, _ := ret[0].(*cf.AccessPolicyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPolicy indicates an expected call of CreateAccessPolicy.
func (mr *MockCloudflareClientMockRecorder) CreateAccessPolicy(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPolicy", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessPolicy), ctx, params)
}

// CreateAccessServiceToken mocks base method.
func (m *MockCloudflareClient) CreateAccessServiceToken(ctx context.Context, name, duration string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessServiceToken", ctx, name, duration)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessServiceToken indicates an expected call of CreateAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) CreateAccessServiceToken(ctx, name, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).CreateAccessServiceToken), ctx, name, duration)
}

// CreateDNSRecord mocks base method.
func (m *MockCloudflareClient) CreateDNSRecord(ctx context.Context, params cf.DNSRecordParams) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDNSRecord", ctx, params)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDNSRecord indicates an expected call of CreateDNSRecord.
func (mr *MockCloudflareClientMockRecorder) CreateDNSRecord(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).CreateDNSRecord), ctx, params)
}

// CreateDevicePostureRule mocks base method.
func (m *MockCloudflareClient) CreateDevicePostureRule(ctx context.Context, params cf.DevicePostureRuleParams) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevicePostureRule", ctx, params)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevicePostureRule indicates an expected call of CreateDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) CreateDevicePostureRule(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).CreateDevicePostureRule), ctx, params)
}

// CreateGatewayList mocks base method.
func (m *MockCloudflareClient) CreateGatewayList(ctx context.Context, params cf.GatewayListParams) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGatewayList", ctx, params)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGatewayList indicates an expected call of CreateGatewayList.
func (mr *MockCloudflareClientMockRecorder) CreateGatewayList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).CreateGatewayList), ctx, params)
}

// CreateGatewayRule mocks base method.
func (m *MockCloudflareClient) CreateGatewayRule(ctx context.Context, params cf.GatewayRuleParams) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGatewayRule", ctx, params)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGatewayRule indicates an expected call of CreateGatewayRule.
func (mr *MockCloudflareClientMockRecorder) CreateGatewayRule(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).CreateGatewayRule), ctx, params)
}

// CreateTunnel mocks base method.
func (m *MockCloudflareClient) CreateTunnel(ctx context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTunnel", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTunnel indicates an expected call of CreateTunnel.
func (mr *MockCloudflareClientMockRecorder) CreateTunnel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTunnel", reflect.TypeOf((*MockCloudflareClient)(nil).CreateTunnel), ctx)
}

// CreateTunnelRoute mocks base method.
func (m *MockCloudflareClient) CreateTunnelRoute(ctx context.Context, params cf.TunnelRouteParams) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTunnelRoute", ctx, params)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTunnelRoute indicates an expected call of CreateTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) CreateTunnelRoute(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).CreateTunnelRoute), ctx, params)
}

// CreateVirtualNetwork mocks base method.
func (m *MockCloudflareClient) CreateVirtualNetwork(ctx context.Context, params cf.VirtualNetworkParams) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVirtualNetwork", ctx, params)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVirtualNetwork indicates an expected call of CreateVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) CreateVirtualNetwork(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).CreateVirtualNetwork), ctx, params)
}

// CreateWARPConnector mocks base method.
func (m *MockCloudflareClient) CreateWARPConnector(ctx context.Context, name string) (*cf.WARPConnectorResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWARPConnector", ctx, name)
	ret0, _ := ret[0].(*cf.WARPConnectorResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWARPConnector indicates an expected call of CreateWARPConnector.
func (mr *MockCloudflareClientMockRecorder) CreateWARPConnector(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWARPConnector", reflect.TypeOf((*MockCloudflareClient)(nil).CreateWARPConnector), ctx, name)
}

// DeleteAccessApplication mocks base method.
func (m *MockCloudflareClient) DeleteAccessApplication(ctx context.Context, applicationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessApplication", ctx, applicationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessApplication indicates an expected call of DeleteAccessApplication.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessApplication(ctx, applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessApplication), ctx, applicationID)
}

// DeleteAccessGroup mocks base method.
func (m *MockCloudflareClient) DeleteAccessGroup(ctx context.Context, groupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessGroup", ctx, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessGroup indicates an expected call of DeleteAccessGroup.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessGroup), ctx, groupID)
}

// DeleteAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) DeleteAccessIdentityProvider(ctx context.Context, idpID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessIdentityProvider", ctx, idpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessIdentityProvider indicates an expected call of DeleteAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessIdentityProvider(ctx, idpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessIdentityProvider), ctx, idpID)
}

// DeleteAccessPolicy mocks base method.
func (m *MockCloudflareClient) DeleteAccessPolicy(ctx context.Context, applicationID, policyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPolicy", ctx, applicationID, policyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessPolicy indicates an expected call of DeleteAccessPolicy.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessPolicy(ctx, applicationID, policyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPolicy", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessPolicy), ctx, applicationID, policyID)
}

// DeleteAccessServiceToken mocks base method.
func (m *MockCloudflareClient) DeleteAccessServiceToken(ctx context.Context, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessServiceToken", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessServiceToken indicates an expected call of DeleteAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) DeleteAccessServiceToken(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteAccessServiceToken), ctx, tokenID)
}

// DeleteDNSId mocks base method.
func (m *MockCloudflareClient) DeleteDNSId(ctx context.Context, fqdn, dnsID string, created bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSId", ctx, fqdn, dnsID, created)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSId indicates an expected call of DeleteDNSId.
func (mr *MockCloudflareClientMockRecorder) DeleteDNSId(ctx, fqdn, dnsID, created any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSId", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDNSId), ctx, fqdn, dnsID, created)
}

// DeleteDNSRecord mocks base method.
func (m *MockCloudflareClient) DeleteDNSRecord(ctx context.Context, zoneID, recordID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSRecord", ctx, zoneID, recordID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSRecord indicates an expected call of DeleteDNSRecord.
func (mr *MockCloudflareClientMockRecorder) DeleteDNSRecord(ctx, zoneID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDNSRecord), ctx, zoneID, recordID)
}

// DeleteDevicePostureRule mocks base method.
func (m *MockCloudflareClient) DeleteDevicePostureRule(ctx context.Context, ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevicePostureRule", ctx, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevicePostureRule indicates an expected call of DeleteDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) DeleteDevicePostureRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteDevicePostureRule), ctx, ruleID)
}

// DeleteGatewayList mocks base method.
func (m *MockCloudflareClient) DeleteGatewayList(ctx context.Context, listID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGatewayList", ctx, listID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGatewayList indicates an expected call of DeleteGatewayList.
func (mr *MockCloudflareClientMockRecorder) DeleteGatewayList(ctx, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteGatewayList), ctx, listID)
}

// DeleteGatewayRule mocks base method.
func (m *MockCloudflareClient) DeleteGatewayRule(ctx context.Context, ruleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGatewayRule", ctx, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGatewayRule indicates an expected call of DeleteGatewayRule.
func (mr *MockCloudflareClientMockRecorder) DeleteGatewayRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteGatewayRule), ctx, ruleID)
}

// DeleteTunnel mocks base method.
func (m *MockCloudflareClient) DeleteTunnel(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTunnel", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTunnel indicates an expected call of DeleteTunnel.
func (mr *MockCloudflareClientMockRecorder) DeleteTunnel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTunnel", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteTunnel), ctx)
}

// DeleteTunnelRoute mocks base method.
func (m *MockCloudflareClient) DeleteTunnelRoute(ctx context.Context, network, virtualNetworkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTunnelRoute", ctx, network, virtualNetworkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTunnelRoute indicates an expected call of DeleteTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) DeleteTunnelRoute(ctx, network, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteTunnelRoute), ctx, network, virtualNetworkID)
}

// DeleteVirtualNetwork mocks base method.
func (m *MockCloudflareClient) DeleteVirtualNetwork(ctx context.Context, virtualNetworkID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVirtualNetwork", ctx, virtualNetworkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVirtualNetwork indicates an expected call of DeleteVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) DeleteVirtualNetwork(ctx, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteVirtualNetwork), ctx, virtualNetworkID)
}

// DeleteWARPConnector mocks base method.
func (m *MockCloudflareClient) DeleteWARPConnector(ctx context.Context, connectorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWARPConnector", ctx, connectorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWARPConnector indicates an expected call of DeleteWARPConnector.
func (mr *MockCloudflareClientMockRecorder) DeleteWARPConnector(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWARPConnector", reflect.TypeOf((*MockCloudflareClient)(nil).DeleteWARPConnector), ctx, connectorID)
}

// GetAccessApplication mocks base method.
func (m *MockCloudflareClient) GetAccessApplication(ctx context.Context, applicationID string) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessApplication", ctx, applicationID)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessApplication indicates an expected call of GetAccessApplication.
func (mr *MockCloudflareClientMockRecorder) GetAccessApplication(ctx, applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessApplication), ctx, applicationID)
}

// GetAccessGroup mocks base method.
func (m *MockCloudflareClient) GetAccessGroup(ctx context.Context, groupID string) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessGroup", ctx, groupID)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessGroup indicates an expected call of GetAccessGroup.
func (mr *MockCloudflareClientMockRecorder) GetAccessGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessGroup), ctx, groupID)
}

// GetAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) GetAccessIdentityProvider(ctx context.Context, idpID string) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessIdentityProvider", ctx, idpID)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessIdentityProvider indicates an expected call of GetAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) GetAccessIdentityProvider(ctx, idpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessIdentityProvider), ctx, idpID)
}

// GetAccessPolicy mocks base method.
func (m *MockCloudflareClient) GetAccessPolicy(ctx context.Context, applicationID, policyID string) (*cf.AccessPolicyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessPolicy", ctx, applicationID, policyID)
	ret0, _ := ret[0].(*cf.AccessPolicyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessPolicy indicates an expected call of GetAccessPolicy.
func (mr *MockCloudflareClientMockRecorder) GetAccessPolicy(ctx, applicationID, policyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessPolicy", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessPolicy), ctx, applicationID, policyID)
}

// GetAccessServiceTokenByName mocks base method.
func (m *MockCloudflareClient) GetAccessServiceTokenByName(ctx context.Context, name string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessServiceTokenByName", ctx, name)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessServiceTokenByName indicates an expected call of GetAccessServiceTokenByName.
func (mr *MockCloudflareClientMockRecorder) GetAccessServiceTokenByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessServiceTokenByName", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccessServiceTokenByName), ctx, name)
}

// GetAccountId mocks base method.
func (m *MockCloudflareClient) GetAccountId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountId indicates an expected call of GetAccountId.
func (mr *MockCloudflareClientMockRecorder) GetAccountId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountId", reflect.TypeOf((*MockCloudflareClient)(nil).GetAccountId), ctx)
}

// GetDNSCNameId mocks base method.
func (m *MockCloudflareClient) GetDNSCNameId(ctx context.Context, fqdn string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSCNameId", ctx, fqdn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSCNameId indicates an expected call of GetDNSCNameId.
func (mr *MockCloudflareClientMockRecorder) GetDNSCNameId(ctx, fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSCNameId", reflect.TypeOf((*MockCloudflareClient)(nil).GetDNSCNameId), ctx, fqdn)
}

// GetDNSRecord mocks base method.
func (m *MockCloudflareClient) GetDNSRecord(ctx context.Context, zoneID, recordID string) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSRecord", ctx, zoneID, recordID)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDNSRecord indicates an expected call of GetDNSRecord.
func (mr *MockCloudflareClientMockRecorder) GetDNSRecord(ctx, zoneID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).GetDNSRecord), ctx, zoneID, recordID)
}

// GetDevicePostureRule mocks base method.
func (m *MockCloudflareClient) GetDevicePostureRule(ctx context.Context, ruleID string) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePostureRule", ctx, ruleID)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePostureRule indicates an expected call of GetDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) GetDevicePostureRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).GetDevicePostureRule), ctx, ruleID)
}

// GetFallbackDomains mocks base method.
func (m *MockCloudflareClient) GetFallbackDomains(ctx context.Context) ([]cf.FallbackDomainEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFallbackDomains", ctx)
	ret0, _ := ret[0].([]cf.FallbackDomainEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFallbackDomains indicates an expected call of GetFallbackDomains.
func (mr *MockCloudflareClientMockRecorder) GetFallbackDomains(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFallbackDomains", reflect.TypeOf((*MockCloudflareClient)(nil).GetFallbackDomains), ctx)
}

// GetGatewayList mocks base method.
func (m *MockCloudflareClient) GetGatewayList(ctx context.Context, listID string) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayList", ctx, listID)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayList indicates an expected call of GetGatewayList.
func (mr *MockCloudflareClientMockRecorder) GetGatewayList(ctx, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).GetGatewayList), ctx, listID)
}

// GetGatewayRule mocks base method.
func (m *MockCloudflareClient) GetGatewayRule(ctx context.Context, ruleID string) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayRule", ctx, ruleID)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayRule indicates an expected call of GetGatewayRule.
func (mr *MockCloudflareClientMockRecorder) GetGatewayRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).GetGatewayRule), ctx, ruleID)
}

// GetManagedDnsTxt mocks base method.
func (m *MockCloudflareClient) GetManagedDnsTxt(ctx context.Context, fqdn string) (string, cf.DnsManagedRecordTxt, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagedDnsTxt", ctx, fqdn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(cf.DnsManagedRecordTxt)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetManagedDnsTxt indicates an expected call of GetManagedDnsTxt.
func (mr *MockCloudflareClientMockRecorder) GetManagedDnsTxt(ctx, fqdn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedDnsTxt", reflect.TypeOf((*MockCloudflareClient)(nil).GetManagedDnsTxt), ctx, fqdn)
}

// GetSplitTunnelExclude mocks base method.
func (m *MockCloudflareClient) GetSplitTunnelExclude(ctx context.Context) ([]cf.SplitTunnelEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSplitTunnelExclude", ctx)
	ret0, _ := ret[0].([]cf.SplitTunnelEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSplitTunnelExclude indicates an expected call of GetSplitTunnelExclude.
func (mr *MockCloudflareClientMockRecorder) GetSplitTunnelExclude(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSplitTunnelExclude", reflect.TypeOf((*MockCloudflareClient)(nil).GetSplitTunnelExclude), ctx)
}

// GetSplitTunnelInclude mocks base method.
func (m *MockCloudflareClient) GetSplitTunnelInclude(ctx context.Context) ([]cf.SplitTunnelEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSplitTunnelInclude", ctx)
	ret0, _ := ret[0].([]cf.SplitTunnelEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSplitTunnelInclude indicates an expected call of GetSplitTunnelInclude.
func (mr *MockCloudflareClientMockRecorder) GetSplitTunnelInclude(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSplitTunnelInclude", reflect.TypeOf((*MockCloudflareClient)(nil).GetSplitTunnelInclude), ctx)
}

// GetTunnelCreds mocks base method.
func (m *MockCloudflareClient) GetTunnelCreds(ctx context.Context, tunnelSecret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelCreds", ctx, tunnelSecret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelCreds indicates an expected call of GetTunnelCreds.
func (mr *MockCloudflareClientMockRecorder) GetTunnelCreds(ctx, tunnelSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelCreds", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelCreds), ctx, tunnelSecret)
}

// GetTunnelId mocks base method.
func (m *MockCloudflareClient) GetTunnelId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelId indicates an expected call of GetTunnelId.
func (mr *MockCloudflareClientMockRecorder) GetTunnelId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelId", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelId), ctx)
}

// GetTunnelRoute mocks base method.
func (m *MockCloudflareClient) GetTunnelRoute(ctx context.Context, network, virtualNetworkID string) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnelRoute", ctx, network, virtualNetworkID)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnelRoute indicates an expected call of GetTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) GetTunnelRoute(ctx, network, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).GetTunnelRoute), ctx, network, virtualNetworkID)
}

// GetVirtualNetwork mocks base method.
func (m *MockCloudflareClient) GetVirtualNetwork(ctx context.Context, virtualNetworkID string) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualNetwork", ctx, virtualNetworkID)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualNetwork indicates an expected call of GetVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) GetVirtualNetwork(ctx, virtualNetworkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).GetVirtualNetwork), ctx, virtualNetworkID)
}

// GetVirtualNetworkByName mocks base method.
func (m *MockCloudflareClient) GetVirtualNetworkByName(ctx context.Context, name string) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualNetworkByName", ctx, name)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualNetworkByName indicates an expected call of GetVirtualNetworkByName.
func (mr *MockCloudflareClientMockRecorder) GetVirtualNetworkByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualNetworkByName", reflect.TypeOf((*MockCloudflareClient)(nil).GetVirtualNetworkByName), ctx, name)
}

// GetWARPConnectorToken mocks base method.
func (m *MockCloudflareClient) GetWARPConnectorToken(ctx context.Context, connectorID string) (*cf.WARPConnectorTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWARPConnectorToken", ctx, connectorID)
	ret0, _ := ret[0].(*cf.WARPConnectorTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWARPConnectorToken indicates an expected call of GetWARPConnectorToken.
func (mr *MockCloudflareClientMockRecorder) GetWARPConnectorToken(ctx, connectorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWARPConnectorToken", reflect.TypeOf((*MockCloudflareClient)(nil).GetWARPConnectorToken), ctx, connectorID)
}

// GetZoneId mocks base method.
func (m *MockCloudflareClient) GetZoneId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneId indicates an expected call of GetZoneId.
func (mr *MockCloudflareClientMockRecorder) GetZoneId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneId", reflect.TypeOf((*MockCloudflareClient)(nil).GetZoneId), ctx)
}

// InsertOrUpdateCName mocks base method.
func (m *MockCloudflareClient) InsertOrUpdateCName(ctx context.Context, fqdn, dnsID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdateCName", ctx, fqdn, dnsID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOrUpdateCName indicates an expected call of InsertOrUpdateCName.
func (mr *MockCloudflareClientMockRecorder) InsertOrUpdateCName(ctx, fqdn, dnsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdateCName", reflect.TypeOf((*MockCloudflareClient)(nil).InsertOrUpdateCName), ctx, fqdn, dnsID)
}

// InsertOrUpdateTXT mocks base method.
func (m *MockCloudflareClient) InsertOrUpdateTXT(ctx context.Context, fqdn, txtID, dnsID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdateTXT", ctx, fqdn, txtID, dnsID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrUpdateTXT indicates an expected call of InsertOrUpdateTXT.
func (mr *MockCloudflareClientMockRecorder) InsertOrUpdateTXT(ctx, fqdn, txtID, dnsID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdateTXT", reflect.TypeOf((*MockCloudflareClient)(nil).InsertOrUpdateTXT), ctx, fqdn, txtID, dnsID)
}

// ListAccessApplicationsByName mocks base method.
func (m *MockCloudflareClient) ListAccessApplicationsByName(ctx context.Context, name string) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessApplicationsByName", ctx, name)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessApplicationsByName indicates an expected call of ListAccessApplicationsByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessApplicationsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessApplicationsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessApplicationsByName), ctx, name)
}

// ListAccessGroupsByName mocks base method.
func (m *MockCloudflareClient) ListAccessGroupsByName(ctx context.Context, name string) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessGroupsByName", ctx, name)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessGroupsByName indicates an expected call of ListAccessGroupsByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessGroupsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessGroupsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessGroupsByName), ctx, name)
}

// ListAccessIdentityProvidersByName mocks base method.
func (m *MockCloudflareClient) ListAccessIdentityProvidersByName(ctx context.Context, name string) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessIdentityProvidersByName", ctx, name)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessIdentityProvidersByName indicates an expected call of ListAccessIdentityProvidersByName.
func (mr *MockCloudflareClientMockRecorder) ListAccessIdentityProvidersByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessIdentityProvidersByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessIdentityProvidersByName), ctx, name)
}

// ListAccessPolicies mocks base method.
func (m *MockCloudflareClient) ListAccessPolicies(ctx context.Context, applicationID string) ([]cf.AccessPolicyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessPolicies", ctx, applicationID)
	ret0, _ := ret[0].([]cf.AccessPolicyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPolicies indicates an expected call of ListAccessPolicies.
func (mr *MockCloudflareClientMockRecorder) ListAccessPolicies(ctx, applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPolicies", reflect.TypeOf((*MockCloudflareClient)(nil).ListAccessPolicies), ctx, applicationID)
}

// ListDevicePostureRulesByName mocks base method.
func (m *MockCloudflareClient) ListDevicePostureRulesByName(ctx context.Context, name string) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevicePostureRulesByName", ctx, name)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevicePostureRulesByName indicates an expected call of ListDevicePostureRulesByName.
func (mr *MockCloudflareClientMockRecorder) ListDevicePostureRulesByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevicePostureRulesByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListDevicePostureRulesByName), ctx, name)
}

// ListGatewayListsByName mocks base method.
func (m *MockCloudflareClient) ListGatewayListsByName(ctx context.Context, name string) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGatewayListsByName", ctx, name)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGatewayListsByName indicates an expected call of ListGatewayListsByName.
func (mr *MockCloudflareClientMockRecorder) ListGatewayListsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGatewayListsByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListGatewayListsByName), ctx, name)
}

// ListGatewayRulesByName mocks base method.
func (m *MockCloudflareClient) ListGatewayRulesByName(ctx context.Context, name string) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGatewayRulesByName", ctx, name)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGatewayRulesByName indicates an expected call of ListGatewayRulesByName.
func (mr *MockCloudflareClientMockRecorder) ListGatewayRulesByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGatewayRulesByName", reflect.TypeOf((*MockCloudflareClient)(nil).ListGatewayRulesByName), ctx, name)
}

// RefreshAccessServiceToken mocks base method.
func (m *MockCloudflareClient) RefreshAccessServiceToken(ctx context.Context, tokenID string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshAccessServiceToken", ctx, tokenID)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshAccessServiceToken indicates an expected call of RefreshAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) RefreshAccessServiceToken(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).RefreshAccessServiceToken), ctx, tokenID)
}

// UpdateAccessApplication mocks base method.
func (m *MockCloudflareClient) UpdateAccessApplication(ctx context.Context, applicationID string, params cf.AccessApplicationParams) (*cf.AccessApplicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessApplication", ctx, applicationID, params)
	ret0, _ := ret[0].(*cf.AccessApplicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessApplication indicates an expected call of UpdateAccessApplication.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessApplication(ctx, applicationID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessApplication", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessApplication), ctx, applicationID, params)
}

// UpdateAccessGroup mocks base method.
func (m *MockCloudflareClient) UpdateAccessGroup(ctx context.Context, groupID string, params cf.AccessGroupParams) (*cf.AccessGroupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessGroup", ctx, groupID, params)
	ret0, _ := ret[0].(*cf.AccessGroupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessGroup indicates an expected call of UpdateAccessGroup.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessGroup(ctx, groupID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessGroup", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessGroup), ctx, groupID, params)
}

// UpdateAccessIdentityProvider mocks base method.
func (m *MockCloudflareClient) UpdateAccessIdentityProvider(ctx context.Context, idpID string, params cf.AccessIdentityProviderParams) (*cf.AccessIdentityProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessIdentityProvider", ctx, idpID, params)
	ret0, _ := ret[0].(*cf.AccessIdentityProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessIdentityProvider indicates an expected call of UpdateAccessIdentityProvider.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessIdentityProvider(ctx, idpID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessIdentityProvider", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessIdentityProvider), ctx, idpID, params)
}

// UpdateAccessPolicy mocks base method.
func (m *MockCloudflareClient) UpdateAccessPolicy(ctx context.Context, policyID string, params cf.AccessPolicyParams) (*cf.AccessPolicyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessPolicy", ctx, policyID, params)
	ret0, _ := ret[0].(*cf.AccessPolicyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessPolicy indicates an expected call of UpdateAccessPolicy.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessPolicy(ctx, policyID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessPolicy", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessPolicy), ctx, policyID, params)
}

// UpdateAccessServiceToken mocks base method.
func (m *MockCloudflareClient) UpdateAccessServiceToken(ctx context.Context, tokenID, name, duration string) (*cf.AccessServiceTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessServiceToken", ctx, tokenID, name, duration)
	ret0, _ := ret[0].(*cf.AccessServiceTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccessServiceToken indicates an expected call of UpdateAccessServiceToken.
func (mr *MockCloudflareClientMockRecorder) UpdateAccessServiceToken(ctx, tokenID, name, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessServiceToken", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateAccessServiceToken), ctx, tokenID, name, duration)
}

// UpdateDNSRecord mocks base method.
func (m *MockCloudflareClient) UpdateDNSRecord(ctx context.Context, zoneID, recordID string, params cf.DNSRecordParams) (*cf.DNSRecordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDNSRecord", ctx, zoneID, recordID, params)
	ret0, _ := ret[0].(*cf.DNSRecordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDNSRecord indicates an expected call of UpdateDNSRecord.
func (mr *MockCloudflareClientMockRecorder) UpdateDNSRecord(ctx, zoneID, recordID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDNSRecord", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateDNSRecord), ctx, zoneID, recordID, params)
}

// UpdateDevicePostureRule mocks base method.
func (m *MockCloudflareClient) UpdateDevicePostureRule(ctx context.Context, ruleID string, params cf.DevicePostureRuleParams) (*cf.DevicePostureRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevicePostureRule", ctx, ruleID, params)
	ret0, _ := ret[0].(*cf.DevicePostureRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevicePostureRule indicates an expected call of UpdateDevicePostureRule.
func (mr *MockCloudflareClientMockRecorder) UpdateDevicePostureRule(ctx, ruleID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevicePostureRule", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateDevicePostureRule), ctx, ruleID, params)
}

// UpdateFallbackDomains mocks base method.
func (m *MockCloudflareClient) UpdateFallbackDomains(ctx context.Context, entries []cf.FallbackDomainEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFallbackDomains", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFallbackDomains indicates an expected call of UpdateFallbackDomains.
func (mr *MockCloudflareClientMockRecorder) UpdateFallbackDomains(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFallbackDomains", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateFallbackDomains), ctx, entries)
}

// UpdateGatewayConfiguration mocks base method.
func (m *MockCloudflareClient) UpdateGatewayConfiguration(ctx context.Context, params cf.GatewayConfigurationParams) (*cf.GatewayConfigurationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayConfiguration", ctx, params)
	ret0, _ := ret[0].(*cf.GatewayConfigurationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayConfiguration indicates an expected call of UpdateGatewayConfiguration.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayConfiguration(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayConfiguration", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayConfiguration), ctx, params)
}

// UpdateGatewayList mocks base method.
func (m *MockCloudflareClient) UpdateGatewayList(ctx context.Context, listID string, params cf.GatewayListParams) (*cf.GatewayListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayList", ctx, listID, params)
	ret0, _ := ret[0].(*cf.GatewayListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayList indicates an expected call of UpdateGatewayList.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayList(ctx, listID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayList", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayList), ctx, listID, params)
}

// UpdateGatewayRule mocks base method.
func (m *MockCloudflareClient) UpdateGatewayRule(ctx context.Context, ruleID string, params cf.GatewayRuleParams) (*cf.GatewayRuleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGatewayRule", ctx, ruleID, params)
	ret0, _ := ret[0].(*cf.GatewayRuleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGatewayRule indicates an expected call of UpdateGatewayRule.
func (mr *MockCloudflareClientMockRecorder) UpdateGatewayRule(ctx, ruleID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGatewayRule", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateGatewayRule), ctx, ruleID, params)
}

// UpdateSplitTunnelExclude mocks base method.
func (m *MockCloudflareClient) UpdateSplitTunnelExclude(ctx context.Context, entries []cf.SplitTunnelEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSplitTunnelExclude", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSplitTunnelExclude indicates an expected call of UpdateSplitTunnelExclude.
func (mr *MockCloudflareClientMockRecorder) UpdateSplitTunnelExclude(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSplitTunnelExclude", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateSplitTunnelExclude), ctx, entries)
}

// UpdateSplitTunnelInclude mocks base method.
func (m *MockCloudflareClient) UpdateSplitTunnelInclude(ctx context.Context, entries []cf.SplitTunnelEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSplitTunnelInclude", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSplitTunnelInclude indicates an expected call of UpdateSplitTunnelInclude.
func (mr *MockCloudflareClientMockRecorder) UpdateSplitTunnelInclude(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSplitTunnelInclude", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateSplitTunnelInclude), ctx, entries)
}

// UpdateTunnelRoute mocks base method.
func (m *MockCloudflareClient) UpdateTunnelRoute(ctx context.Context, network string, params cf.TunnelRouteParams) (*cf.TunnelRouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTunnelRoute", ctx, network, params)
	ret0, _ := ret[0].(*cf.TunnelRouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTunnelRoute indicates an expected call of UpdateTunnelRoute.
func (mr *MockCloudflareClientMockRecorder) UpdateTunnelRoute(ctx, network, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTunnelRoute", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateTunnelRoute), ctx, network, params)
}

// UpdateVirtualNetwork mocks base method.
func (m *MockCloudflareClient) UpdateVirtualNetwork(ctx context.Context, virtualNetworkID string, params cf.VirtualNetworkParams) (*cf.VirtualNetworkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVirtualNetwork", ctx, virtualNetworkID, params)
	ret0, _ := ret[0].(*cf.VirtualNetworkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVirtualNetwork indicates an expected call of UpdateVirtualNetwork.
func (mr *MockCloudflareClientMockRecorder) UpdateVirtualNetwork(ctx, virtualNetworkID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVirtualNetwork", reflect.TypeOf((*MockCloudflareClient)(nil).UpdateVirtualNetwork), ctx, virtualNetworkID, params)
}

// ValidateAll mocks base method.
func (m *MockCloudflareClient) ValidateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAll indicates an expected call of ValidateAll.
func (mr *MockCloudflareClientMockRecorder) ValidateAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAll", reflect.TypeOf((*MockCloudflareClient)(nil).ValidateAll), ctx)
}
