name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature belong to?
      options:
        - Tunnel Management
        - Private Network (VirtualNetwork, NetworkRoute)
        - Access Control (Applications, Groups, Identity Providers)
        - Gateway & Security
        - Device Management
        - DNS & Connectivity
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: manifest
    attributes:
      label: Proposed API/Manifest
      description: If applicable, show what the resource manifest might look like.
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
