//go:build !ignore_autogenerated

/*
Copyright 2025 Adyanth H.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplication) DeepCopyInto(out *AccessApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplication.
func (in *AccessApplication) DeepCopy() *AccessApplication {
	if in == nil {
		return nil
	}
	out := new(AccessApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationList) DeepCopyInto(out *AccessApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationList.
func (in *AccessApplicationList) DeepCopy() *AccessApplicationList {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationSpec) DeepCopyInto(out *AccessApplicationSpec) {
	*out = *in
	if in.AllowedIdps != nil {
		in, out := &in.AllowedIdps, &out.AllowedIdps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedIdpRefs != nil {
		in, out := &in.AllowedIdpRefs, &out.AllowedIdpRefs
		*out = make([]AccessIdentityProviderRef, len(*in))
		copy(*out, *in)
	}
	if in.EnableBindingCookie != nil {
		in, out := &in.EnableBindingCookie, &out.EnableBindingCookie
		*out = new(bool)
		**out = **in
	}
	if in.HttpOnlyCookieAttribute != nil {
		in, out := &in.HttpOnlyCookieAttribute, &out.HttpOnlyCookieAttribute
		*out = new(bool)
		**out = **in
	}
	if in.SkipInterstitial != nil {
		in, out := &in.SkipInterstitial, &out.SkipInterstitial
		*out = new(bool)
		**out = **in
	}
	if in.AppLauncherVisible != nil {
		in, out := &in.AppLauncherVisible, &out.AppLauncherVisible
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAuth401Redirect != nil {
		in, out := &in.ServiceAuth401Redirect, &out.ServiceAuth401Redirect
		*out = new(bool)
		**out = **in
	}
	if in.AllowAuthenticateViaWarp != nil {
		in, out := &in.AllowAuthenticateViaWarp, &out.AllowAuthenticateViaWarp
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AccessPolicyRef, len(*in))
		copy(*out, *in)
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationSpec.
func (in *AccessApplicationSpec) DeepCopy() *AccessApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessApplicationStatus) DeepCopyInto(out *AccessApplicationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessApplicationStatus.
func (in *AccessApplicationStatus) DeepCopy() *AccessApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(AccessApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroup) DeepCopyInto(out *AccessGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroup.
func (in *AccessGroup) DeepCopy() *AccessGroup {
	if in == nil {
		return nil
	}
	out := new(AccessGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupAzureRule) DeepCopyInto(out *AccessGroupAzureRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupAzureRule.
func (in *AccessGroupAzureRule) DeepCopy() *AccessGroupAzureRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupAzureRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupCommonNameRule) DeepCopyInto(out *AccessGroupCommonNameRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupCommonNameRule.
func (in *AccessGroupCommonNameRule) DeepCopy() *AccessGroupCommonNameRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupCommonNameRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupCountryRule) DeepCopyInto(out *AccessGroupCountryRule) {
	*out = *in
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupCountryRule.
func (in *AccessGroupCountryRule) DeepCopy() *AccessGroupCountryRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupCountryRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupDevicePostureRule) DeepCopyInto(out *AccessGroupDevicePostureRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupDevicePostureRule.
func (in *AccessGroupDevicePostureRule) DeepCopy() *AccessGroupDevicePostureRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupDevicePostureRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupEmailDomainRule) DeepCopyInto(out *AccessGroupEmailDomainRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupEmailDomainRule.
func (in *AccessGroupEmailDomainRule) DeepCopy() *AccessGroupEmailDomainRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupEmailDomainRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupEmailRule) DeepCopyInto(out *AccessGroupEmailRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupEmailRule.
func (in *AccessGroupEmailRule) DeepCopy() *AccessGroupEmailRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupEmailRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupExternalEvaluationRule) DeepCopyInto(out *AccessGroupExternalEvaluationRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupExternalEvaluationRule.
func (in *AccessGroupExternalEvaluationRule) DeepCopy() *AccessGroupExternalEvaluationRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupExternalEvaluationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupGSuiteRule) DeepCopyInto(out *AccessGroupGSuiteRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupGSuiteRule.
func (in *AccessGroupGSuiteRule) DeepCopy() *AccessGroupGSuiteRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupGSuiteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupGitHubRule) DeepCopyInto(out *AccessGroupGitHubRule) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupGitHubRule.
func (in *AccessGroupGitHubRule) DeepCopy() *AccessGroupGitHubRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupGitHubRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupGroupRule) DeepCopyInto(out *AccessGroupGroupRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupGroupRule.
func (in *AccessGroupGroupRule) DeepCopy() *AccessGroupGroupRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupIPRangesRule) DeepCopyInto(out *AccessGroupIPRangesRule) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupIPRangesRule.
func (in *AccessGroupIPRangesRule) DeepCopy() *AccessGroupIPRangesRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupIPRangesRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupList) DeepCopyInto(out *AccessGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupList.
func (in *AccessGroupList) DeepCopy() *AccessGroupList {
	if in == nil {
		return nil
	}
	out := new(AccessGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupOIDCRule) DeepCopyInto(out *AccessGroupOIDCRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupOIDCRule.
func (in *AccessGroupOIDCRule) DeepCopy() *AccessGroupOIDCRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupOIDCRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupRule) DeepCopyInto(out *AccessGroupRule) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(AccessGroupEmailRule)
		**out = **in
	}
	if in.EmailDomain != nil {
		in, out := &in.EmailDomain, &out.EmailDomain
		*out = new(AccessGroupEmailDomainRule)
		**out = **in
	}
	if in.IPRanges != nil {
		in, out := &in.IPRanges, &out.IPRanges
		*out = new(AccessGroupIPRangesRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(AccessGroupCountryRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(AccessGroupGroupRule)
		**out = **in
	}
	if in.ServiceToken != nil {
		in, out := &in.ServiceToken, &out.ServiceToken
		*out = new(AccessGroupServiceTokenRule)
		**out = **in
	}
	if in.CommonName != nil {
		in, out := &in.CommonName, &out.CommonName
		*out = new(AccessGroupCommonNameRule)
		**out = **in
	}
	if in.DevicePosture != nil {
		in, out := &in.DevicePosture, &out.DevicePosture
		*out = new(AccessGroupDevicePostureRule)
		**out = **in
	}
	if in.GSuite != nil {
		in, out := &in.GSuite, &out.GSuite
		*out = new(AccessGroupGSuiteRule)
		**out = **in
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(AccessGroupGitHubRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AccessGroupAzureRule)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(AccessGroupOIDCRule)
		**out = **in
	}
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(AccessGroupSAMLRule)
		**out = **in
	}
	if in.ExternalEvaluation != nil {
		in, out := &in.ExternalEvaluation, &out.ExternalEvaluation
		*out = new(AccessGroupExternalEvaluationRule)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupRule.
func (in *AccessGroupRule) DeepCopy() *AccessGroupRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupSAMLRule) DeepCopyInto(out *AccessGroupSAMLRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupSAMLRule.
func (in *AccessGroupSAMLRule) DeepCopy() *AccessGroupSAMLRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupSAMLRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupServiceTokenRule) DeepCopyInto(out *AccessGroupServiceTokenRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupServiceTokenRule.
func (in *AccessGroupServiceTokenRule) DeepCopy() *AccessGroupServiceTokenRule {
	if in == nil {
		return nil
	}
	out := new(AccessGroupServiceTokenRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupSpec) DeepCopyInto(out *AccessGroupSpec) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]AccessGroupRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]AccessGroupRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = make([]AccessGroupRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupSpec.
func (in *AccessGroupSpec) DeepCopy() *AccessGroupSpec {
	if in == nil {
		return nil
	}
	out := new(AccessGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessGroupStatus) DeepCopyInto(out *AccessGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessGroupStatus.
func (in *AccessGroupStatus) DeepCopy() *AccessGroupStatus {
	if in == nil {
		return nil
	}
	out := new(AccessGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIdentityProvider) DeepCopyInto(out *AccessIdentityProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIdentityProvider.
func (in *AccessIdentityProvider) DeepCopy() *AccessIdentityProvider {
	if in == nil {
		return nil
	}
	out := new(AccessIdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessIdentityProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIdentityProviderList) DeepCopyInto(out *AccessIdentityProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessIdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIdentityProviderList.
func (in *AccessIdentityProviderList) DeepCopy() *AccessIdentityProviderList {
	if in == nil {
		return nil
	}
	out := new(AccessIdentityProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessIdentityProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIdentityProviderRef) DeepCopyInto(out *AccessIdentityProviderRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIdentityProviderRef.
func (in *AccessIdentityProviderRef) DeepCopy() *AccessIdentityProviderRef {
	if in == nil {
		return nil
	}
	out := new(AccessIdentityProviderRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIdentityProviderSpec) DeepCopyInto(out *AccessIdentityProviderSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(IdentityProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIdentityProviderSpec.
func (in *AccessIdentityProviderSpec) DeepCopy() *AccessIdentityProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AccessIdentityProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessIdentityProviderStatus) DeepCopyInto(out *AccessIdentityProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessIdentityProviderStatus.
func (in *AccessIdentityProviderStatus) DeepCopy() *AccessIdentityProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AccessIdentityProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicyRef) DeepCopyInto(out *AccessPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicyRef.
func (in *AccessPolicyRef) DeepCopy() *AccessPolicyRef {
	if in == nil {
		return nil
	}
	out := new(AccessPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessServiceToken) DeepCopyInto(out *AccessServiceToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessServiceToken.
func (in *AccessServiceToken) DeepCopy() *AccessServiceToken {
	if in == nil {
		return nil
	}
	out := new(AccessServiceToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessServiceToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessServiceTokenList) DeepCopyInto(out *AccessServiceTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessServiceToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessServiceTokenList.
func (in *AccessServiceTokenList) DeepCopy() *AccessServiceTokenList {
	if in == nil {
		return nil
	}
	out := new(AccessServiceTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessServiceTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessServiceTokenSpec) DeepCopyInto(out *AccessServiceTokenSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessServiceTokenSpec.
func (in *AccessServiceTokenSpec) DeepCopy() *AccessServiceTokenSpec {
	if in == nil {
		return nil
	}
	out := new(AccessServiceTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessServiceTokenStatus) DeepCopyInto(out *AccessServiceTokenStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessServiceTokenStatus.
func (in *AccessServiceTokenStatus) DeepCopy() *AccessServiceTokenStatus {
	if in == nil {
		return nil
	}
	out := new(AccessServiceTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivityLogSettings) DeepCopyInto(out *ActivityLogSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivityLogSettings.
func (in *ActivityLogSettings) DeepCopy() *ActivityLogSettings {
	if in == nil {
		return nil
	}
	out := new(ActivityLogSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AntiVirusSettings) DeepCopyInto(out *AntiVirusSettings) {
	*out = *in
	if in.NotificationSettings != nil {
		in, out := &in.NotificationSettings, &out.NotificationSettings
		*out = new(NotificationSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AntiVirusSettings.
func (in *AntiVirusSettings) DeepCopy() *AntiVirusSettings {
	if in == nil {
		return nil
	}
	out := new(AntiVirusSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditSSHSettings) DeepCopyInto(out *AuditSSHSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditSSHSettings.
func (in *AuditSSHSettings) DeepCopy() *AuditSSHSettings {
	if in == nil {
		return nil
	}
	out := new(AuditSSHSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoPopulateConfig) DeepCopyInto(out *AutoPopulateConfig) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoPopulateConfig.
func (in *AutoPopulateConfig) DeepCopy() *AutoPopulateConfig {
	if in == nil {
		return nil
	}
	out := new(AutoPopulateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BISOAdminControls) DeepCopyInto(out *BISOAdminControls) {
	*out = *in
	if in.DisablePrinting != nil {
		in, out := &in.DisablePrinting, &out.DisablePrinting
		*out = new(bool)
		**out = **in
	}
	if in.DisableCopyPaste != nil {
		in, out := &in.DisableCopyPaste, &out.DisableCopyPaste
		*out = new(bool)
		**out = **in
	}
	if in.DisableDownload != nil {
		in, out := &in.DisableDownload, &out.DisableDownload
		*out = new(bool)
		**out = **in
	}
	if in.DisableUpload != nil {
		in, out := &in.DisableUpload, &out.DisableUpload
		*out = new(bool)
		**out = **in
	}
	if in.DisableKeyboard != nil {
		in, out := &in.DisableKeyboard, &out.DisableKeyboard
		*out = new(bool)
		**out = **in
	}
	if in.DisableClipboardRedirection != nil {
		in, out := &in.DisableClipboardRedirection, &out.DisableClipboardRedirection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BISOAdminControls.
func (in *BISOAdminControls) DeepCopy() *BISOAdminControls {
	if in == nil {
		return nil
	}
	out := new(BISOAdminControls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockPageSettings) DeepCopyInto(out *BlockPageSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockPageSettings.
func (in *BlockPageSettings) DeepCopy() *BlockPageSettings {
	if in == nil {
		return nil
	}
	out := new(BlockPageSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyScanningSettings) DeepCopyInto(out *BodyScanningSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyScanningSettings.
func (in *BodyScanningSettings) DeepCopy() *BodyScanningSettings {
	if in == nil {
		return nil
	}
	out := new(BodyScanningSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrowserIsolationSettings) DeepCopyInto(out *BrowserIsolationSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrowserIsolationSettings.
func (in *BrowserIsolationSettings) DeepCopy() *BrowserIsolationSettings {
	if in == nil {
		return nil
	}
	out := new(BrowserIsolationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDetails) DeepCopyInto(out *CloudflareDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDetails.
func (in *CloudflareDetails) DeepCopy() *CloudflareDetails {
	if in == nil {
		return nil
	}
	out := new(CloudflareDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTunnel) DeepCopyInto(out *ClusterTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTunnel.
func (in *ClusterTunnel) DeepCopy() *ClusterTunnel {
	if in == nil {
		return nil
	}
	out := new(ClusterTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTunnelList) DeepCopyInto(out *ClusterTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTunnelList.
func (in *ClusterTunnelList) DeepCopy() *ClusterTunnelList {
	if in == nil {
		return nil
	}
	out := new(ClusterTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCertificateSettings) DeepCopyInto(out *CustomCertificateSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCertificateSettings.
func (in *CustomCertificateSettings) DeepCopy() *CustomCertificateSettings {
	if in == nil {
		return nil
	}
	out := new(CustomCertificateSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecord) DeepCopyInto(out *DNSRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecord.
func (in *DNSRecord) DeepCopy() *DNSRecord {
	if in == nil {
		return nil
	}
	out := new(DNSRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordData) DeepCopyInto(out *DNSRecordData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordData.
func (in *DNSRecordData) DeepCopy() *DNSRecordData {
	if in == nil {
		return nil
	}
	out := new(DNSRecordData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordList) DeepCopyInto(out *DNSRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordList.
func (in *DNSRecordList) DeepCopy() *DNSRecordList {
	if in == nil {
		return nil
	}
	out := new(DNSRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSpec) DeepCopyInto(out *DNSRecordSpec) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(DNSRecordData)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSpec.
func (in *DNSRecordSpec) DeepCopy() *DNSRecordSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordStatus) DeepCopyInto(out *DNSRecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordStatus.
func (in *DNSRecordStatus) DeepCopy() *DNSRecordStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSResolver) DeepCopyInto(out *DNSResolver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSResolver.
func (in *DNSResolver) DeepCopy() *DNSResolver {
	if in == nil {
		return nil
	}
	out := new(DNSResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureInput) DeepCopyInto(out *DevicePostureInput) {
	*out = *in
	if in.Exists != nil {
		in, out := &in.Exists, &out.Exists
		*out = new(bool)
		**out = **in
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(bool)
		**out = **in
	}
	if in.RequireAll != nil {
		in, out := &in.RequireAll, &out.RequireAll
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ActiveThreats != nil {
		in, out := &in.ActiveThreats, &out.ActiveThreats
		*out = new(int)
		**out = **in
	}
	if in.IssueCount != nil {
		in, out := &in.IssueCount, &out.IssueCount
		*out = new(int)
		**out = **in
	}
	if in.CheckDisks != nil {
		in, out := &in.CheckDisks, &out.CheckDisks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureInput.
func (in *DevicePostureInput) DeepCopy() *DevicePostureInput {
	if in == nil {
		return nil
	}
	out := new(DevicePostureInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureMatch) DeepCopyInto(out *DevicePostureMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureMatch.
func (in *DevicePostureMatch) DeepCopy() *DevicePostureMatch {
	if in == nil {
		return nil
	}
	out := new(DevicePostureMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRule) DeepCopyInto(out *DevicePostureRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRule.
func (in *DevicePostureRule) DeepCopy() *DevicePostureRule {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleList) DeepCopyInto(out *DevicePostureRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevicePostureRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleList.
func (in *DevicePostureRuleList) DeepCopy() *DevicePostureRuleList {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevicePostureRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleSpec) DeepCopyInto(out *DevicePostureRuleSpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]DevicePostureMatch, len(*in))
		copy(*out, *in)
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(DevicePostureInput)
		(*in).DeepCopyInto(*out)
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleSpec.
func (in *DevicePostureRuleSpec) DeepCopy() *DevicePostureRuleSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevicePostureRuleStatus) DeepCopyInto(out *DevicePostureRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevicePostureRuleStatus.
func (in *DevicePostureRuleStatus) DeepCopy() *DevicePostureRuleStatus {
	if in == nil {
		return nil
	}
	out := new(DevicePostureRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicy) DeepCopyInto(out *DeviceSettingsPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicy.
func (in *DeviceSettingsPolicy) DeepCopy() *DeviceSettingsPolicy {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSettingsPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyList) DeepCopyInto(out *DeviceSettingsPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceSettingsPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyList.
func (in *DeviceSettingsPolicyList) DeepCopy() *DeviceSettingsPolicyList {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceSettingsPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicySpec) DeepCopyInto(out *DeviceSettingsPolicySpec) {
	*out = *in
	if in.SplitTunnelExclude != nil {
		in, out := &in.SplitTunnelExclude, &out.SplitTunnelExclude
		*out = make([]SplitTunnelEntry, len(*in))
		copy(*out, *in)
	}
	if in.SplitTunnelInclude != nil {
		in, out := &in.SplitTunnelInclude, &out.SplitTunnelInclude
		*out = make([]SplitTunnelEntry, len(*in))
		copy(*out, *in)
	}
	if in.FallbackDomains != nil {
		in, out := &in.FallbackDomains, &out.FallbackDomains
		*out = make([]FallbackDomainEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoPopulateFromRoutes != nil {
		in, out := &in.AutoPopulateFromRoutes, &out.AutoPopulateFromRoutes
		*out = new(AutoPopulateConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicySpec.
func (in *DeviceSettingsPolicySpec) DeepCopy() *DeviceSettingsPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSettingsPolicyStatus) DeepCopyInto(out *DeviceSettingsPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSettingsPolicyStatus.
func (in *DeviceSettingsPolicyStatus) DeepCopy() *DeviceSettingsPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceSettingsPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressSettings) DeepCopyInto(out *EgressSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressSettings.
func (in *EgressSettings) DeepCopy() *EgressSettings {
	if in == nil {
		return nil
	}
	out := new(EgressSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExistingTunnel) DeepCopyInto(out *ExistingTunnel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExistingTunnel.
func (in *ExistingTunnel) DeepCopy() *ExistingTunnel {
	if in == nil {
		return nil
	}
	out := new(ExistingTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FIPSSettings) DeepCopyInto(out *FIPSSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FIPSSettings.
func (in *FIPSSettings) DeepCopy() *FIPSSettings {
	if in == nil {
		return nil
	}
	out := new(FIPSSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackDomainEntry) DeepCopyInto(out *FallbackDomainEntry) {
	*out = *in
	if in.DNSServer != nil {
		in, out := &in.DNSServer, &out.DNSServer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackDomainEntry.
func (in *FallbackDomainEntry) DeepCopy() *FallbackDomainEntry {
	if in == nil {
		return nil
	}
	out := new(FallbackDomainEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfiguration) DeepCopyInto(out *GatewayConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfiguration.
func (in *GatewayConfiguration) DeepCopy() *GatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfigurationList) DeepCopyInto(out *GatewayConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfigurationList.
func (in *GatewayConfigurationList) DeepCopy() *GatewayConfigurationList {
	if in == nil {
		return nil
	}
	out := new(GatewayConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfigurationSpec) DeepCopyInto(out *GatewayConfigurationSpec) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfigurationSpec.
func (in *GatewayConfigurationSpec) DeepCopy() *GatewayConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfigurationStatus) DeepCopyInto(out *GatewayConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfigurationStatus.
func (in *GatewayConfigurationStatus) DeepCopy() *GatewayConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayList) DeepCopyInto(out *GatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayList.
func (in *GatewayList) DeepCopy() *GatewayList {
	if in == nil {
		return nil
	}
	out := new(GatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayListItem) DeepCopyInto(out *GatewayListItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayListItem.
func (in *GatewayListItem) DeepCopy() *GatewayListItem {
	if in == nil {
		return nil
	}
	out := new(GatewayListItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayListList) DeepCopyInto(out *GatewayListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayListList.
func (in *GatewayListList) DeepCopy() *GatewayListList {
	if in == nil {
		return nil
	}
	out := new(GatewayListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayListSpec) DeepCopyInto(out *GatewayListSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayListItem, len(*in))
		copy(*out, *in)
	}
	if in.ItemsFromConfigMap != nil {
		in, out := &in.ItemsFromConfigMap, &out.ItemsFromConfigMap
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayListSpec.
func (in *GatewayListSpec) DeepCopy() *GatewayListSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayListStatus) DeepCopyInto(out *GatewayListStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayListStatus.
func (in *GatewayListStatus) DeepCopy() *GatewayListStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRule) DeepCopyInto(out *GatewayRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRule.
func (in *GatewayRule) DeepCopy() *GatewayRule {
	if in == nil {
		return nil
	}
	out := new(GatewayRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRuleList) DeepCopyInto(out *GatewayRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRuleList.
func (in *GatewayRuleList) DeepCopy() *GatewayRuleList {
	if in == nil {
		return nil
	}
	out := new(GatewayRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRuleSettings) DeepCopyInto(out *GatewayRuleSettings) {
	*out = *in
	if in.BlockPageEnabled != nil {
		in, out := &in.BlockPageEnabled, &out.BlockPageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OverrideIPs != nil {
		in, out := &in.OverrideIPs, &out.OverrideIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.L4Override != nil {
		in, out := &in.L4Override, &out.L4Override
		*out = new(L4OverrideSettings)
		**out = **in
	}
	if in.BISOAdminControls != nil {
		in, out := &in.BISOAdminControls, &out.BISOAdminControls
		*out = new(BISOAdminControls)
		(*in).DeepCopyInto(*out)
	}
	if in.CheckSession != nil {
		in, out := &in.CheckSession, &out.CheckSession
		*out = new(SessionSettings)
		**out = **in
	}
	if in.AddHeaders != nil {
		in, out := &in.AddHeaders, &out.AddHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InsecureDisableDNSSECValidation != nil {
		in, out := &in.InsecureDisableDNSSECValidation, &out.InsecureDisableDNSSECValidation
		*out = new(bool)
		**out = **in
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(EgressSettings)
		**out = **in
	}
	if in.PayloadLog != nil {
		in, out := &in.PayloadLog, &out.PayloadLog
		*out = new(PayloadLogSettings)
		**out = **in
	}
	if in.AuditSSH != nil {
		in, out := &in.AuditSSH, &out.AuditSSH
		*out = new(AuditSSHSettings)
		**out = **in
	}
	if in.ResolveDNSInternally != nil {
		in, out := &in.ResolveDNSInternally, &out.ResolveDNSInternally
		*out = new(bool)
		**out = **in
	}
	if in.DNSResolverIPv4 != nil {
		in, out := &in.DNSResolverIPv4, &out.DNSResolverIPv4
		*out = new(DNSResolver)
		**out = **in
	}
	if in.DNSResolverIPv6 != nil {
		in, out := &in.DNSResolverIPv6, &out.DNSResolverIPv6
		*out = new(DNSResolver)
		**out = **in
	}
	if in.NotificationSettings != nil {
		in, out := &in.NotificationSettings, &out.NotificationSettings
		*out = new(NotificationSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRuleSettings.
func (in *GatewayRuleSettings) DeepCopy() *GatewayRuleSettings {
	if in == nil {
		return nil
	}
	out := new(GatewayRuleSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRuleSpec) DeepCopyInto(out *GatewayRuleSpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuleSettings != nil {
		in, out := &in.RuleSettings, &out.RuleSettings
		*out = new(GatewayRuleSettings)
		(*in).DeepCopyInto(*out)
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRuleSpec.
func (in *GatewayRuleSpec) DeepCopy() *GatewayRuleSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRuleStatus) DeepCopyInto(out *GatewayRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRuleStatus.
func (in *GatewayRuleStatus) DeepCopy() *GatewayRuleStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySettings) DeepCopyInto(out *GatewaySettings) {
	*out = *in
	if in.TLSDecrypt != nil {
		in, out := &in.TLSDecrypt, &out.TLSDecrypt
		*out = new(TLSDecryptSettings)
		**out = **in
	}
	if in.ActivityLog != nil {
		in, out := &in.ActivityLog, &out.ActivityLog
		*out = new(ActivityLogSettings)
		**out = **in
	}
	if in.AntiVirus != nil {
		in, out := &in.AntiVirus, &out.AntiVirus
		*out = new(AntiVirusSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockPage != nil {
		in, out := &in.BlockPage, &out.BlockPage
		*out = new(BlockPageSettings)
		**out = **in
	}
	if in.BodyScanning != nil {
		in, out := &in.BodyScanning, &out.BodyScanning
		*out = new(BodyScanningSettings)
		**out = **in
	}
	if in.BrowserIsolation != nil {
		in, out := &in.BrowserIsolation, &out.BrowserIsolation
		*out = new(BrowserIsolationSettings)
		**out = **in
	}
	if in.FIPS != nil {
		in, out := &in.FIPS, &out.FIPS
		*out = new(FIPSSettings)
		**out = **in
	}
	if in.ProtocolDetection != nil {
		in, out := &in.ProtocolDetection, &out.ProtocolDetection
		*out = new(ProtocolDetectionSettings)
		**out = **in
	}
	if in.CustomCertificate != nil {
		in, out := &in.CustomCertificate, &out.CustomCertificate
		*out = new(CustomCertificateSettings)
		**out = **in
	}
	if in.NonIdentityBrowserIsolation != nil {
		in, out := &in.NonIdentityBrowserIsolation, &out.NonIdentityBrowserIsolation
		*out = new(NonIdentityBrowserIsolationSettings)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySettings.
func (in *GatewaySettings) DeepCopy() *GatewaySettings {
	if in == nil {
		return nil
	}
	out := new(GatewaySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityProviderConfig) DeepCopyInto(out *IdentityProviderConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdPPublicCerts != nil {
		in, out := &in.IdPPublicCerts, &out.IdPPublicCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SignRequest != nil {
		in, out := &in.SignRequest, &out.SignRequest
		*out = new(bool)
		**out = **in
	}
	if in.SupportGroups != nil {
		in, out := &in.SupportGroups, &out.SupportGroups
		*out = new(bool)
		**out = **in
	}
	if in.PKCEEnabled != nil {
		in, out := &in.PKCEEnabled, &out.PKCEEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConditionalAccessEnabled != nil {
		in, out := &in.ConditionalAccessEnabled, &out.ConditionalAccessEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HeaderAttributes != nil {
		in, out := &in.HeaderAttributes, &out.HeaderAttributes
		*out = make([]SAMLHeaderAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityProviderConfig.
func (in *IdentityProviderConfig) DeepCopy() *IdentityProviderConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4OverrideSettings) DeepCopyInto(out *L4OverrideSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4OverrideSettings.
func (in *L4OverrideSettings) DeepCopy() *L4OverrideSettings {
	if in == nil {
		return nil
	}
	out := new(L4OverrideSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRoute) DeepCopyInto(out *NetworkRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRoute.
func (in *NetworkRoute) DeepCopy() *NetworkRoute {
	if in == nil {
		return nil
	}
	out := new(NetworkRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouteList) DeepCopyInto(out *NetworkRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouteList.
func (in *NetworkRouteList) DeepCopy() *NetworkRouteList {
	if in == nil {
		return nil
	}
	out := new(NetworkRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouteSpec) DeepCopyInto(out *NetworkRouteSpec) {
	*out = *in
	out.TunnelRef = in.TunnelRef
	if in.VirtualNetworkRef != nil {
		in, out := &in.VirtualNetworkRef, &out.VirtualNetworkRef
		*out = new(VirtualNetworkRef)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouteSpec.
func (in *NetworkRouteSpec) DeepCopy() *NetworkRouteSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRouteStatus) DeepCopyInto(out *NetworkRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRouteStatus.
func (in *NetworkRouteStatus) DeepCopy() *NetworkRouteStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewTunnel) DeepCopyInto(out *NewTunnel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewTunnel.
func (in *NewTunnel) DeepCopy() *NewTunnel {
	if in == nil {
		return nil
	}
	out := new(NewTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonIdentityBrowserIsolationSettings) DeepCopyInto(out *NonIdentityBrowserIsolationSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonIdentityBrowserIsolationSettings.
func (in *NonIdentityBrowserIsolationSettings) DeepCopy() *NonIdentityBrowserIsolationSettings {
	if in == nil {
		return nil
	}
	out := new(NonIdentityBrowserIsolationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSettings) DeepCopyInto(out *NotificationSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSettings.
func (in *NotificationSettings) DeepCopy() *NotificationSettings {
	if in == nil {
		return nil
	}
	out := new(NotificationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PayloadLogSettings) DeepCopyInto(out *PayloadLogSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PayloadLogSettings.
func (in *PayloadLogSettings) DeepCopy() *PayloadLogSettings {
	if in == nil {
		return nil
	}
	out := new(PayloadLogSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateService) DeepCopyInto(out *PrivateService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateService.
func (in *PrivateService) DeepCopy() *PrivateService {
	if in == nil {
		return nil
	}
	out := new(PrivateService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateServiceList) DeepCopyInto(out *PrivateServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateServiceList.
func (in *PrivateServiceList) DeepCopy() *PrivateServiceList {
	if in == nil {
		return nil
	}
	out := new(PrivateServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateServiceSpec) DeepCopyInto(out *PrivateServiceSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	out.TunnelRef = in.TunnelRef
	if in.VirtualNetworkRef != nil {
		in, out := &in.VirtualNetworkRef, &out.VirtualNetworkRef
		*out = new(VirtualNetworkRef)
		**out = **in
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateServiceSpec.
func (in *PrivateServiceSpec) DeepCopy() *PrivateServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateServiceStatus) DeepCopyInto(out *PrivateServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateServiceStatus.
func (in *PrivateServiceStatus) DeepCopy() *PrivateServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolDetectionSettings) DeepCopyInto(out *ProtocolDetectionSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolDetectionSettings.
func (in *ProtocolDetectionSettings) DeepCopy() *ProtocolDetectionSettings {
	if in == nil {
		return nil
	}
	out := new(ProtocolDetectionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLHeaderAttribute) DeepCopyInto(out *SAMLHeaderAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLHeaderAttribute.
func (in *SAMLHeaderAttribute) DeepCopy() *SAMLHeaderAttribute {
	if in == nil {
		return nil
	}
	out := new(SAMLHeaderAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTokenSecretRef) DeepCopyInto(out *ServiceTokenSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTokenSecretRef.
func (in *ServiceTokenSecretRef) DeepCopy() *ServiceTokenSecretRef {
	if in == nil {
		return nil
	}
	out := new(ServiceTokenSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSettings) DeepCopyInto(out *SessionSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSettings.
func (in *SessionSettings) DeepCopy() *SessionSettings {
	if in == nil {
		return nil
	}
	out := new(SessionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplitTunnelEntry) DeepCopyInto(out *SplitTunnelEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplitTunnelEntry.
func (in *SplitTunnelEntry) DeepCopy() *SplitTunnelEntry {
	if in == nil {
		return nil
	}
	out := new(SplitTunnelEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSDecryptSettings) DeepCopyInto(out *TLSDecryptSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSDecryptSettings.
func (in *TLSDecryptSettings) DeepCopy() *TLSDecryptSettings {
	if in == nil {
		return nil
	}
	out := new(TLSDecryptSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Toleration) DeepCopyInto(out *Toleration) {
	*out = *in
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Toleration.
func (in *Toleration) DeepCopy() *Toleration {
	if in == nil {
		return nil
	}
	out := new(Toleration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tunnel) DeepCopyInto(out *Tunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tunnel.
func (in *Tunnel) DeepCopy() *Tunnel {
	if in == nil {
		return nil
	}
	out := new(Tunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelList) DeepCopyInto(out *TunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelList.
func (in *TunnelList) DeepCopy() *TunnelList {
	if in == nil {
		return nil
	}
	out := new(TunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRef) DeepCopyInto(out *TunnelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRef.
func (in *TunnelRef) DeepCopy() *TunnelRef {
	if in == nil {
		return nil
	}
	out := new(TunnelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelSpec) DeepCopyInto(out *TunnelSpec) {
	*out = *in
	out.Cloudflare = in.Cloudflare
	if in.ExistingTunnel != nil {
		in, out := &in.ExistingTunnel, &out.ExistingTunnel
		*out = new(ExistingTunnel)
		**out = **in
	}
	if in.NewTunnel != nil {
		in, out := &in.NewTunnel, &out.NewTunnel
		*out = new(NewTunnel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelSpec.
func (in *TunnelSpec) DeepCopy() *TunnelSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelStatus) DeepCopyInto(out *TunnelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelStatus.
func (in *TunnelStatus) DeepCopy() *TunnelStatus {
	if in == nil {
		return nil
	}
	out := new(TunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetwork) DeepCopyInto(out *VirtualNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetwork.
func (in *VirtualNetwork) DeepCopy() *VirtualNetwork {
	if in == nil {
		return nil
	}
	out := new(VirtualNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkList) DeepCopyInto(out *VirtualNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkList.
func (in *VirtualNetworkList) DeepCopy() *VirtualNetworkList {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkRef) DeepCopyInto(out *VirtualNetworkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkRef.
func (in *VirtualNetworkRef) DeepCopy() *VirtualNetworkRef {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkSpec) DeepCopyInto(out *VirtualNetworkSpec) {
	*out = *in
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkSpec.
func (in *VirtualNetworkSpec) DeepCopy() *VirtualNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNetworkStatus) DeepCopyInto(out *VirtualNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNetworkStatus.
func (in *VirtualNetworkStatus) DeepCopy() *VirtualNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPConnector) DeepCopyInto(out *WARPConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPConnector.
func (in *WARPConnector) DeepCopy() *WARPConnector {
	if in == nil {
		return nil
	}
	out := new(WARPConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WARPConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPConnectorList) DeepCopyInto(out *WARPConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WARPConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPConnectorList.
func (in *WARPConnectorList) DeepCopy() *WARPConnectorList {
	if in == nil {
		return nil
	}
	out := new(WARPConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WARPConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPConnectorRoute) DeepCopyInto(out *WARPConnectorRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPConnectorRoute.
func (in *WARPConnectorRoute) DeepCopy() *WARPConnectorRoute {
	if in == nil {
		return nil
	}
	out := new(WARPConnectorRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPConnectorSpec) DeepCopyInto(out *WARPConnectorSpec) {
	*out = *in
	if in.VirtualNetworkRef != nil {
		in, out := &in.VirtualNetworkRef, &out.VirtualNetworkRef
		*out = new(VirtualNetworkRef)
		**out = **in
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]WARPConnectorRoute, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Cloudflare = in.Cloudflare
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPConnectorSpec.
func (in *WARPConnectorSpec) DeepCopy() *WARPConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(WARPConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WARPConnectorStatus) DeepCopyInto(out *WARPConnectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WARPConnectorStatus.
func (in *WARPConnectorStatus) DeepCopy() *WARPConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(WARPConnectorStatus)
	in.DeepCopyInto(out)
	return out
}
